
name: UnitTests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # This workflow contains a single job called "unit_tests"
  unit_tests:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
          compiler-version: [[g++-13, gcc-13]]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packages
        run: |
            sudo apt-get update -qq
            sudo apt-get install build-essential cmake make libboost-all-dev

      - name: Build and compile
        env:
          COMPILER: ${{ matrix.compiler-version[0] }}
        run: |
          export CC=gcc-13 CXX=g++-13
          mkdir build && cd build
          cmake ..
          make

      - name: Run Unit-Tests
        run: |
          ./build/test/tests -l all